export const initialData = {
  workshops: [
    {
      name: "Ale's Workshop",
      location: "Santa Clara",
      speciality: "Hybrid Vehicle Specialists",
      ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
      imageUrl: "/imgs/workshops/image_0.png",
      rating: 4,
    },
    {
      name: "Jose's Workshop",
      location: "Ciudad Quesada",
      speciality: "Brake Repair",
      ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
      imageUrl: "/imgs/workshops/image_1.png",
      rating: 3,
    },
    {
        name: "John's Workshop",
        location: "La Fortuna",
        speciality: "Factory Trained Technicians",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_2.png",
        rating: 2,
    },
    {
        name: "Jane's Workshop",
        location: "Escazu",
        speciality: "Tire and Wheel Alignment",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_3.png",
        rating: 5,
    },
    {
        name: "Jill's Workshop",
        location: "Florencia",
        speciality: "Oil Change and Lube Service",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_4.png",
        rating: 1,
    },
    {
        name: "Jack's Workshop",
        location: "Puntarenas",
        speciality: "Engine Repair and Diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_5.png",
        rating: 4,
    },
    {
        name: "Joe's Workshop",
        location: "Guanacaste",
        speciality: "Transmission Repair",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_6.png",
        rating: 3,
    },
    {
        name: "Jenny's Workshop",
        location: "Limon",
        speciality: "Electrical Repair and Diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_7.png",
        rating: 2,
    },
    {
        name: "Claudio's Workshop",
        location: "Grecia",
        speciality: "Suspension Repair and Diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_8.png",
        rating: 5,
    },
   {
        name: "Keylor's Workshop",
        location: "Esparza",
        speciality: "Fuel System Repair and Diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_9.png",
        rating: 1,
   },
   {
        name: "Fred's Workshop",
        location: "Monteverde",
        speciality: "Factory Trained Technicians",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_10.png",
        rating: 4,
   },
   {
        name: "Fernando's Workshop",
        location: "Florencia",
        speciality: "Cooling system repair and diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_11.png",
        rating: 3,
   },
   {
        name: "Fernanda's Workshop",
        location: "Jaco",
        speciality: "General repair and diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_12.png",
        rating: 2,
   },
   {
        name: "Juancho's Workshop",
        location: "Heredia",
        speciality: "Brake repair and diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_13.png",
        rating: 5,
   },
   {
        name: "Frederick's Workshop",
        location: "San Jose",
        speciality: "Transmission repair and diagnostics",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_14.png",
        rating: 1,
   },
   {
        name: "Osvaldo's Workshop",
        location: "Montes de Oca",
        speciality: "R",
        ownerId: "37310d6b-9abd-4439-94a4-e0cb38ca1bd4",
        imageUrl: "/imgs/workshops/image_15.png",
        rating: 4,
   }

  ],
};
