import bcryptjs from 'bcryptjs';



export const initialData = {
  workshops: [
    {
      id: 1,
      name: "Ale's Workshop",
      location: "Santa Clara",
      speciality: "Hybrid Vehicle Specialists",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_0.png",
      rating: 4,
    },
    {
      id: 2,
      name: "Jose's Workshop",
      location: "Ciudad Quesada",
      speciality: "Brake Repair",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_1.png",
      rating: 3,
    },
    {
      id: 3,
      name: "John's Workshop",
      location: "La Fortuna",
      speciality: "Factory Trained Technicians",
      ownerId: "a-2",
      imageUrl: "/imgs/workshops/image_2.png",
      rating: 2,
    },
    {
      id: 4,
      name: "Jane's Workshop",
      location: "Escazu",
      speciality: "Tire and Wheel Alignment",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_3.png",
      rating: 5,
    },
    {
      id: 5,
      name: "Jill's Workshop",
      location: "Florencia",
      speciality: "Oil Change and Lube Service",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_4.png",
      rating: 1,
    },
    {
      id: 6,
      name: "Jack's Workshop",
      location: "Puntarenas",
      speciality: "Engine Repair and Diagnostics",
      ownerId: "a-2",
      imageUrl: "/imgs/workshops/image_5.png",
      rating: 4,
    },
    {
      id: 7,
      name: "Joe's Workshop",
      location: "Guanacaste",
      speciality: "Transmission Repair",
      ownerId: "a-3",
      imageUrl: "/imgs/workshops/image_6.png",
      rating: 3,
    },
    {
      id: 8,
      name: "Jenny's Workshop",
      location: "Limon",
      speciality: "Electrical Repair and Diagnostics",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_7.png",
      rating: 2,
    },
    {
      id: 9,
      name: "Claudio's Workshop",
      location: "Grecia",
      speciality: "Suspension Repair and Diagnostics",
      ownerId: "a-3",
      imageUrl: "/imgs/workshops/image_8.png",
      rating: 5,
    },
    {
      id: 10,
      name: "Keylor's Workshop",
      location: "Esparza",
      speciality: "Fuel System Repair and Diagnostics",
      ownerId: "a-3",
      imageUrl: "/imgs/workshops/image_9.png",
      rating: 1,
    },
    {
      id: 11,
      name: "Fred's Workshop",
      location: "Monteverde",
      speciality: "Factory Trained Technicians",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_10.png",
      rating: 4,
    },
    {
      id: 12,
      name: "Fernando's Workshop",
      location: "Florencia",
      speciality: "Cooling system repair and diagnostics",
      ownerId: "a-2",
      imageUrl: "/imgs/workshops/image_11.png",
      rating: 3,
    },
    {
      id: 13,
      name: "Fernanda's Workshop",
      location: "Jaco",
      speciality: "General repair and diagnostics",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_12.png",
      rating: 2,
    },
    {
      id: 14,
      name: "Juancho's Workshop",
      location: "Heredia",
      speciality: "Brake repair and diagnostics",
      ownerId: "a-1",
      imageUrl: "/imgs/workshops/image_13.png",
      rating: 5,
    },
    {
      id: 15,
      name: "Frederick's Workshop",
      location: "San Jose",
      speciality: "Transmission repair and diagnostics",
      ownerId: "a-2",
      imageUrl: "/imgs/workshops/image_14.png",
      rating: 1,
    },
    {
      id: 16,
      name: "Osvaldo's Workshop",
      location: "Montes de Oca",
      speciality: "R",
      ownerId: "a-2",
      imageUrl: "/imgs/workshops/image_15.png",
      rating: 4,
    },
  ],
  clients: [
    {
      id : 1,
      name: "Client One",
      email: "client1@example.com",
      password: bcryptjs.hashSync("123456", 10)
    },
    {
      id : 2,
      name: "Client Two",
      email: "client2@example.com",
      password: bcryptjs.hashSync("123456", 10)
    },
    {
      id : 3,
      name: "Client Three",
      email: "client3@example.com",
      password: bcryptjs.hashSync("123456", 10)
    },
    {
      id : 4,
      name: "Client Four",
      email: "client4@example.com",
      password: bcryptjs.hashSync("123456", 10)
    },
    {
      id : 5,
      name: "Client Five",
      email: "client5@example.com",
      password: bcryptjs.hashSync("123456", 10)
    },
  ],
  mechanics: [
    { name: "Juan", workshopId: 1 },
    { name: "Fernando", workshopId: 1 },
    { name: "Pedro", workshopId: 2 },
    { name: "Francisco", workshopId: 2 },
    { name: "Jose", workshopId: 3 },
    { name: "Luis", workshopId: 4 },
    { name: "Carlos", workshopId: 5 },
  ],
  users: [
    { id: "a-1", name: "Admin", email: "ale@ale.com", password: bcryptjs.hashSync("123456", 10)},
    { id: "a-2", name: "Admin2", email: "jose@jose.com", password: bcryptjs.hashSync("123456", 10) },
    { id: "a-3", name: "Admin", email: "luis@luis.com", password: bcryptjs.hashSync("123456", 10) },
  ],
  vehicles: [
    {
      id: 1,
      make: "Toyota",
      model: "Corolla",
      year: 2017,
      ownerId: 1,
    },
    {
      id: 2,
      make: "Honda",
      model: "Civic",
      year: 2018,
      ownerId: 2,
    },
    {
      id: 3,
      make: "Ford",
      model: "F-150",
      year: 2019,
      ownerId: 3,
    },
    {
      id: 4,
      make: "Chevrolet",
      model: "Silverado",
      year: 2020,
      ownerId: 4,
    },
    {
      id: 5,
      make: "Toyota",
      model: "Tacoma",
      year: 2021,
      ownerId: 5,
    }
  ],
 
  
};
