export const initialData = {
  workshops: [
    {
      name: "Ale's Workshop",
      location: "Santa Clara",
      speciality: "Hybrid Vehicle Specialists",
      owner: "Owner 1",
      imageUrl: "/imgs/image_0.png",
      rating: 4,
    },
    {
      name: "Jose's Workshop",
      location: "Ciudad Quesada",
      speciality: "Brake Repair",
      owner: "Owner 2",
      imageUrl: "/imgs/image_1.png",
      rating: 3,
    },
    {
        name: "John's Workshop",
        location: "La Fortuna",
        speciality: "Factory Trained Technicians",
        owner: "Owner 3",
        imageUrl: "/imgs/image_2.png",
        rating: 2,
    },
    {
        name: "Jane's Workshop",
        location: "Escazu",
        speciality: "Tire and Wheel Alignment",
        owner: "Owner 4",
        imageUrl: "/imgs/image_3.png",
        rating: 5,
    },
    {
        name: "Jill's Workshop",
        location: "Florencia",
        speciality: "Oil Change and Lube Service",
        owner: "Owner 5",
        imageUrl: "/imgs/image_4.png",
        rating: 1,
    },
    {
        name: "Jack's Workshop",
        location: "Puntarenas",
        speciality: "Engine Repair and Diagnostics",
        owner: "Owner 6",
        imageUrl: "/imgs/image_5.png",
        rating: 4,
    },
    {
        name: "Joe's Workshop",
        location: "Guanacaste",
        speciality: "Transmission Repair",
        owner: "Owner 7",
        imageUrl: "/imgs/image_6.png",
        rating: 3,
    },
    {
        name: "Jenny's Workshop",
        location: "Limon",
        speciality: "Electrical Repair and Diagnostics",
        owner: "Owner 8",
        imageUrl: "/imgs/image_7.png",
        rating: 2,
    },
    {
        name: "Claudio's Workshop",
        location: "Grecia",
        speciality: "Suspension Repair and Diagnostics",
        owner: "Owner 9",
        imageUrl: "/imgs/image_8.png",
        rating: 5,
    },
   {
        name: "Keylor's Workshop",
        location: "Esparza",
        speciality: "Fuel System Repair and Diagnostics",
        owner: "Owner 10",
        imageUrl: "/imgs/image_9.png",
        rating: 1,
   },
   {
        name: "Fred's Workshop",
        location: "Monteverde",
        speciality: "Factory Trained Technicians",
        owner: "Owner 11",
        imageUrl: "/imgs/image_10.png",
        rating: 4,
   },
   {
        name: "Fernando's Workshop",
        location: "Florencia",
        speciality: "Cooling system repair and diagnostics",
        owner: "Owner 12",
        imageUrl: "/imgs/image_11.png",
        rating: 3,
   },
   {
        name: "Fernanda's Workshop",
        location: "Jaco",
        speciality: "General repair and diagnostics",
        owner: "Owner 13",
        imageUrl: "/imgs/image_12.png",
        rating: 2,
   },
   {
        name: "Juancho's Workshop",
        location: "Heredia",
        speciality: "Brake repair and diagnostics",
        owner: "Owner 14",
        imageUrl: "/imgs/image_13.png",
        rating: 5,
   },
   {
        name: "Frederick's Workshop",
        location: "San Jose",
        speciality: "Transmission repair and diagnostics",
        owner: "Owner 15",
        imageUrl: "/imgs/image_14.png",
        rating: 1,
   },
   {
        name: "Osvaldo's Workshop",
        location: "Montes de Oca",
        speciality: "Radiator repair and diagnostics",
        owner: "Owner 16",
        imageUrl: "/imgs/image_15.png",
        rating: 4,
   }

  ],
};
